# Generated by Django 3.0.5 on 2021-10-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magnus_library_user',
            name='user_aadhar_photo',
            field=models.ImageField(default='photo', upload_to='user_aadhaar_photo'),
        ),
        migrations.AddField(
            model_name='magnus_library_user',
            name='user_photo',
            field=models.ImageField(default='photo', upload_to='user_photos'),
        ),
    ]
