# Generated by Django 3.0.5 on 2021-10-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211021_0948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_photos',
        ),
        migrations.RemoveField(
            model_name='magnus_library_user',
            name='user_type',
        ),
    ]
