# Generated by Django 3.0.5 on 2021-10-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('book_isbn', models.PositiveIntegerField()),
                ('book_author', models.CharField(max_length=40)),
                ('book_publicaton', models.CharField(max_length=50)),
                ('book_category', models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('comics', 'Comics'), ('biography', 'Biography'), ('history', 'History'), ('novel', 'Novel'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('scifi', 'Sci-Fi'), ('children', 'Children')], default='education', max_length=30)),
                ('book_type', models.CharField(choices=[('HardCopy', 'Hard Copy'), ('SoftCopy', 'Soft Copy')], default='HardCopy', max_length=30)),
                ('book_quantity', models.PositiveIntegerField()),
                ('book_pages', models.PositiveIntegerField()),
                ('book_price', models.PositiveIntegerField()),
                ('book_edition', models.PositiveIntegerField()),
                ('book_dateofpurchase', models.DateTimeField()),
                ('book_currentholder', models.CharField(default='Admin', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BookHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_currentholder', models.CharField(max_length=30)),
                ('book_id', models.CharField(max_length=30)),
                ('book_issueddate', models.DateTimeField()),
                ('book_returndate', models.DateTimeField()),
                ('book_fine', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.PositiveIntegerField()),
                ('book_id', models.PositiveIntegerField()),
                ('fine', models.PositiveIntegerField(default=0)),
                ('paid_status', models.BooleanField(default=True)),
                ('paid_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[(0, 'Basic'), (1, 'Prime')], default=0, max_length=30)),
                ('subscription_amount', models.PositiveIntegerField(default=0)),
                ('max_no_books', models.PositiveIntegerField(default=4)),
            ],
        ),
    ]
