# Generated by Django 3.0.5 on 2021-10-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='book_photos/photo.png', upload_to='book_photos'),
        ),
    ]
