# Generated by Django 3.0.5 on 2021-11-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20211030_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_owner',
            field=models.CharField(default='Admin', max_length=30),
        ),
    ]
