# Generated by Django 3.0.5 on 2021-11-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_sale',
            field=models.BooleanField(default=False),
        ),
    ]
