# Generated by Django 3.0.5 on 2021-11-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_request_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('comics', 'Comics'), ('biography', 'Biography'), ('history', 'History'), ('novel', 'Novel'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('scifi', 'Sci-Fi'), ('children', 'Children')], default='education', max_length=30)),
                ('genre_image', models.ImageField(default='genre_photos/genre_default.jpg', upload_to='genre_photos')),
            ],
        ),
    ]
