# Generated by Django 3.0.5 on 2021-11-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20211108_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='genre_name',
            field=models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('comics', 'Comics'), ('biography', 'Biography'), ('history', 'History'), ('novel', 'Novel'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('scifi', 'Sci-Fi'), ('children', 'Children'), ('science', 'Science')], default='education', max_length=30),
        ),
    ]
